### PR TITLE
Wave 11

### PR DESCRIPTION
**Pull request by Kharnete**
-Translated all the cards (and added the missing ones) from the last wave.
-Added 'ship' tags to the new Starviper and Khiraxz pilots.

### CODE REVIEW

**Comment by Kharnete** [comment]
Welp, time to search where I fucked it up :P

**Comment by Kharnete** [comment]
I can't find where the hell is the error I made in the second commit. I thought it could be certain blank space I had on Kashyyyk Defender, but doesn't seem to be the case. Both the format and names seem to be correct, but something *must* be wrong somewhere.

If you can't find it either, scrap this all and I will remade it from scratch just in case.

**Comment by geordanr** [comment]
It was an extra space after `Karthakk Pirate`.

**Comment by Kharnete** [comment]
I'm blind and stupid. 5 times 

I checked everything, holy cow :(

**Pull request merged**
