### PR TITLE
Imperial Veterans DE

### PR DESCRIPTION
**Pull request by cbmainz**
German translation of Imperial Veterans

### CODE REVIEW

**Comment by cbmainz** [comment]
Imperial Veterans have been published in Germany.

**Comment by cbmainz** [comment]
I have no experience with these errors above. What can I do to prevent them?

**Comment by strikegun** [comment]
Hi cbmainz, I talk in english so everyone can read this. I think you have tabstops in the code, instead of spaces. was my mistake also. But I uploaded the german veterans already. But if you want to help we can chat outside git to cooperate, I often have less time and would appreciate if I have a partner.

**Comment by cbmainz** [comment]
Yes, indeed, I used tabletops. Thanks for the hint.

Yes we should get in contact, maybe I can help from time to time.

**Pull request closed without merging**
