### PR TITLE
Obstacles choice modal, plus saving/loading obstacles from backend

### PR DESCRIPTION
**Pull request by zacharyp**
Hello Geordan,

Here's an initial pull request that would appreciate your input.

Current PR:

* Adds a Obstacles choice modal, and saves the choices to additional_data for the squad.
* Adds the obstacles to the permalink (for future use in Vassal).
* Saves obstacles to backend, and loads from saved obstacles.

Good placement on the "Choose Obstacles" button?  Thoughts on the popup?

Future:

* Add the obstacles to XWS output
* Add images to the obstacle choices
* Change the print options  for obstacles (quite a bit of work here, I think)
* tests?

### CODE REVIEW

**Comment by zacharyp** [comment]
screen shot 2017-02-15 at 7 10 04 am
screen shot 2017-02-15 at 7 10 20 am

**Comment by geordanr** [comment]
Looks good so far!

I'm thinking of using the X-Wing fonts to display which obstacles are selected, and have created [an issue](https://github.com/geordanr/xwing-miniatures-font/issues/18) to have the obstacles added to the font.  That way we could display the obstacles themselves and have something like click handlers on them that select the appropriate obstacle name from the select (which we could then hide).

The printout would have to change, but I think that could be done by changing that one big image into a series of obstacle icons that we toggle `.hidden` on based on whether they've been selected.

**Comment by zacharyp** [comment]
The issue for obstacles using a png is excellent 👍 

I won't be able to make any changes for the next few days, until at earliest the 21st.

Let me know if there's anything pressing, but otherwise, I think the base modal would be good for now?

**Comment by geordanr** [comment]
Can we add some text that describes its current use case?  I'm worried that putting it out as it is will confuse people as without a visual aid people won't know which obstacle token is what, and the printout won't be coordinated with their choices and so it will look like the feature is buggy.

**Comment by zacharyp** [comment]
Clarification text added.  I'll keep at adding image mouse-over for the select choices, but I would think that would come in a later pull request.

**Pull request merged**
