### PR TITLE
Guns for Hire Expansion Pack (DE)

### PR DESCRIPTION
**Pull request by cbmainz**
Guns for Hire Expansion Pack

### CODE REVIEW

**Comment by geordanr** [comment]
This may have been superseded by #517 -- please check and confirm.

**Comment by cbmainz** [comment]
[#517](https://github.com/geordanr/xwing/pull/517) has some changes I don't have and vice versa. 
I don't know what the compiling error means.

**Comment by cbmainz** [comment]
I tried to solve the problem, but I don't know if it worked out.

**Comment by cbmainz** [comment]
So it looks all is fine now?

**Pull request merged**
